

# =========================================
# Question:
# Find total revenue generated by each product
#
# Final output:
# product_name
# total_revenue
#
# Sort by total_revenue descending.
# =========================================

# Import libraries
import pandas as pd

# Create DataFrames
orders = pd.DataFrame({
    "order_id": [1,2,3,4,5,6,7,8],
    "customer_id": [101,102,101,103,102,101,103,102],
    "product_id": [11,12,13,11,13,12,12,11],
    "quantity": [2,1,3,1,2,1,4,2]
})

products = pd.DataFrame({
    "product_id": [11,12,13],
    "product_name": ["Laptop","Mouse","Keyboard"],
    "price": [50000,500,2000]
})

# Solution 
df = orders.merge(products, on='product_id')

df['revenue'] = df['quantity'] * df['price']

result = df.groupby('product_name').agg(
    total_revenue=('revenue', 'sum')
).reset_index().sort_values(
    by='total_revenue',
    ascending=False
)

print(result)
